// Generated by Helipod. Do not edit.
export { query, mutation, action, httpAction, httpRouter } from "@helipod/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
export type { Internal } from "./internal";
export { cronJobs } from "@helipod/scheduler";
import { anyApi } from "@helipod/client";
import type { Api } from "./api";
import type { Internal } from "./internal";
export const api = anyApi as Api;
export const internal = anyApi as Internal;

// Component context contributions (ctx.<component>), typed.
declare module "@helipod/executor" {
  interface QueryCtx {
    auth: import("@helipod/auth").AuthContext;
    scheduler: import("@helipod/scheduler").SchedulerContext;
    workflow: import("@helipod/workflow").WorkflowContext;
  }
  interface MutationCtx {
    auth: import("@helipod/auth").AuthContext;
    scheduler: import("@helipod/scheduler").SchedulerContext;
    workflow: import("@helipod/workflow").WorkflowContext;
  }
}
