// Generated by Helipod. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "f1": {
    ping: FunctionReference<"query", "public", any, any>;
  };
  "f2": {
    list: FunctionReference<"query", "public", any, any>;
  };
};

export type UdfPathOf<A> = {
  [M in keyof A & string]: {
    [F in keyof A[M] & string]: `${M}:${F}`;
  }[keyof A[M] & string];
}[keyof A & string];
