// Generated by Stackbase. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "audit": {
    _onChange: FunctionReference<"mutation", "public", any, any>;
  };
  "messages": {
    list: FunctionReference<"query", "public", { conversationId: Id<"conversations"> }, Array<{ _id: Id<"messages">; _creationTime: number; conversationId: Id<"conversations">; author: string; body: string }>>;
    listPaginated: FunctionReference<"query", "public", any, any>;
    send: FunctionReference<"mutation", "public", { conversationId: Id<"conversations">; author: string; body: string }, Id<"messages">>;
  };
};
