// Generated by Stackbase. Do not edit.
import type { GenericId } from "@stackbase/values";

export interface DataModel {
  conversations: { document: { _id: Id<"conversations">; _creationTime: number; title: string } };
  messages: { document: { _id: Id<"messages">; _creationTime: number; conversationId: Id<"conversations">; author: string; body: string } };
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
