// Generated by Stackbase. Do not edit.
export { query, mutation, action } from "@stackbase/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
