// Generated by Stackbase. Do not edit.
import type { GenericId } from "@stackbase/values";

export interface DataModel {
  _storage: { document: { _id: Id<"_storage">; _creationTime: number; status: ("pending" | "ready"); key: string; size: (number | null); contentType: (string | null); sha256: (string | null); visibility: ("private" | "public"); expiresAt: (number | null) } };
  notes: { document: { _id: Id<"notes">; _creationTime: number; box: string; text: string; pinned?: boolean } };
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
