// Generated by Helipod. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "options": {
    list: FunctionReference<"query", "public", { pollId: Id<"polls"> }, Array<{ _id: Id<"options">; _creationTime: number; pollId: Id<"polls">; label: string; votes: number; order: number }>>;
    vote: FunctionReference<"mutation", "public", { id: Id<"options"> }, number>;
  };
  "polls": {
    create: FunctionReference<"mutation", "public", { question: string; options: Array<string> }, Id<"polls">>;
    list: FunctionReference<"query", "public", {}, Array<{ _id: Id<"polls">; _creationTime: number; question: string; closed: boolean }>>;
    setClosed: FunctionReference<"mutation", "public", { id: Id<"polls">; closed: boolean }, null>;
  };
};

export type UdfPathOf<A> = {
  [M in keyof A & string]: {
    [F in keyof A[M] & string]: `${M}:${F}`;
  }[keyof A[M] & string];
}[keyof A & string];
