// Generated by Helipod. Do not edit.
import type { GenericId } from "@helipod/values";

export interface DataModel {
  _storage: { document: { _id: Id<"_storage">; _creationTime: number; status: ("pending" | "ready"); key: string; size: (number | null); contentType: (string | null); sha256: (string | null); visibility: ("private" | "public"); expiresAt: (number | null) } };
  lists: { document: { _id: Id<"lists">; _creationTime: number; name: string; locked: boolean } };
  items: { document: { _id: Id<"items">; _creationTime: number; listId: Id<"lists">; label: string; done: boolean } };
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
