// Generated by Stackbase. Do not edit.
import type { GenericId } from "@stackbase/values";

export interface DataModel {

}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
