// Generated by Stackbase. Do not edit.
import { mintEncodedDocumentId } from "@stackbase/id-codec";
import type { Id, TableNames } from "./dataModel";

/** Table numbers for THIS deployment's app tables (embedded in document ids). Regenerate via
 *  `stackbase dev`/`stackbase codegen` against the live deployment lineage — the server
 *  validates every client-minted id at insert, so a stale map fails loudly, never silently. */
export const tableNumbers = {

} as const;

/** Mint a REAL id client-side (same format and entropy as server minting). Mint at
 *  args-construction time, OUTSIDE optimistic updaters (minting is random; updaters must stay
 *  replay-pure and read the id FROM args). Pass it as `_id` to an insert and reference it
 *  freely in later queued mutations — see the offline guide's create-then-reference section. */
export function mintId<T extends TableNames>(table: T): Id<T> {
  const num = tableNumbers[table as keyof typeof tableNumbers];
  if (num === undefined) throw new Error(`unknown table "${String(table)}" — regenerate _generated/`);
  return mintEncodedDocumentId(num) as unknown as Id<T>;
}
