/**
 * Pure generator for the Cloudflare Worker/DO entrypoint (`worker.ts`), Task 7. This is the DO-native
 * twin of `stackbase build`'s `generateEntrySource` (`packages/cli/src/build-entry.ts`): a Worker
 * bundle can no more dir-scan `convex/` than a `bun build --compile` binary can, so we emit STATIC
 * imports of every app module + schema + `stackbase.config.ts` + composed components, and reconstruct
 * the `{ schema, modules }` shape `loadProject` consumes at DO-boot time (§4.2). `JSON.stringify` on
 * every path/key guards against quotes/backslashes breaking the generated source.
 *
 * The emitted module exports BOTH:
 *   - `export default` — the stateless Worker (`createWorkerHandler(bindingName)`), and
 *   - `export class StackbaseDO` — the concrete Durable Object the app's `wrangler.jsonc` names
 *     (a DO binding requires a concrete exported class — §8.8).
 *
 * NO top-level `await` (unlike the single-binary entry): a Worker module must be synchronous at the
 * top level; boot happens lazily inside the DO constructor's `blockConcurrencyWhile` instead.
 */
export interface WorkerEntryInputs {
  moduleImports: Array<{ key: string; absPath: string }>;
  schemaAbsPath: string;
  configAbsPath: string | null;
  /** The `durable_objects` binding name in `wrangler.jsonc` (e.g. `"STACKBASE_DO"`). */
  bindingName: string;
  /** The exported DO class name the `wrangler.jsonc` migration references (e.g. `"StackbaseDO"`). */
  doClassName: string;
  /** The env var the admin key is read from at DO boot (default `STACKBASE_ADMIN_KEY`). */
  adminKeyEnvVar?: string;
  /** The import specifier for the host package — overridable for the in-repo fixture. */
  hostPackage?: string;
}

export function generateWorkerEntrySource(inp: WorkerEntryInputs): string {
  const host = inp.hostPackage ?? "@stackbase/runtime-cloudflare";
  const adminEnv = inp.adminKeyEnvVar ?? "STACKBASE_ADMIN_KEY";
  const L: string[] = ["// AUTO-GENERATED by `@stackbase/runtime-cloudflare` worker-entry — do not edit."];
  inp.moduleImports.forEach((m, i) => L.push(`import * as m${i} from ${JSON.stringify(m.absPath)};`));
  L.push(`import schema from ${JSON.stringify(inp.schemaAbsPath)};`);
  if (inp.configAbsPath) L.push(`import * as __config from ${JSON.stringify(inp.configAbsPath)};`);
  L.push(`import { StackbaseDurableObject, createWorkerHandler } from ${JSON.stringify(host)};`);
  L.push("");
  const modEntries = inp.moduleImports.map((m, i) => `${JSON.stringify(m.key)}: m${i}`).join(", ");
  L.push(`const loaded = { schema: (schema && schema.default) ?? schema, modules: { ${modEntries} } };`);
  L.push(inp.configAbsPath ? `const components = (__config.default ?? __config).components ?? [];` : `const components = [];`);
  L.push("");
  L.push(`export class ${inp.doClassName} extends StackbaseDurableObject {`);
  L.push(`  appConfig(env) {`);
  L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "" };`);
  L.push(`  }`);
  L.push(`}`);
  L.push("");
  L.push(`export default createWorkerHandler(${JSON.stringify(inp.bindingName)});`);
  return L.join("\n") + "\n";
}
