/**
 * Pure generator for the Cloudflare Worker/DO entrypoint (`worker.ts`), Task 7. This is the DO-native
 * twin of `helipod build`'s `generateEntrySource` (`packages/cli/src/build-entry.ts`): a Worker
 * bundle can no more dir-scan `convex/` than a `bun build --compile` binary can, so we emit STATIC
 * imports of every app module + schema + `helipod.config.ts` + composed components, and reconstruct
 * the `{ schema, modules }` shape `loadProject` consumes at DO-boot time (§4.2). `JSON.stringify` on
 * every path/key guards against quotes/backslashes breaking the generated source.
 *
 * The emitted module exports BOTH:
 *   - `export default` — the stateless Worker (`createWorkerHandler(bindingName)`), and
 *   - `export class HelipodDO` — the concrete Durable Object the app's `wrangler.jsonc` names
 *     (a DO binding requires a concrete exported class — §8.8).
 *
 * NO top-level `await` (unlike the single-binary entry): a Worker module must be synchronous at the
 * top level; boot happens lazily inside the DO constructor's `blockConcurrencyWhile` instead.
 */
export interface WorkerEntryInputs {
  moduleImports: Array<{ key: string; absPath: string }>;
  schemaAbsPath: string;
  configAbsPath: string | null;
  /** The `durable_objects` binding name in `wrangler.jsonc` (e.g. `"HELIPOD_DO"`). */
  bindingName: string;
  /** The exported DO class name the `wrangler.jsonc` migration references (e.g. `"HelipodDO"`). */
  doClassName: string;
  /** The env var the admin key is read from at DO boot (default `HELIPOD_ADMIN_KEY`). */
  adminKeyEnvVar?: string;
  /** The import specifier for the host package — overridable for the in-repo fixture. */
  hostPackage?: string;
  /**
   * The `r2_buckets` binding name in `wrangler.jsonc` (e.g. `"STORAGE_BUCKET"`). Set to enable file
   * storage: the generated `appConfig` constructs an `R2BlobStore` over `env[r2BindingName]` and
   * threads it as `blobStore`, so `ctx.storage` + the `/api/storage/*` routes work on the deployed DO.
   * Absent → no R2 import, `blobStore` omitted, file storage inert (byte-less deploy, unchanged).
   */
  r2BindingName?: string;
}

export function generateWorkerEntrySource(inp: WorkerEntryInputs): string {
  const host = inp.hostPackage ?? "@helipod/runtime-cloudflare";
  const adminEnv = inp.adminKeyEnvVar ?? "HELIPOD_ADMIN_KEY";
  const r2 = inp.r2BindingName;
  const L: string[] = ["// AUTO-GENERATED by `@helipod/runtime-cloudflare` worker-entry — do not edit."];
  inp.moduleImports.forEach((m, i) => L.push(`import * as m${i} from ${JSON.stringify(m.absPath)};`));
  L.push(`import schema from ${JSON.stringify(inp.schemaAbsPath)};`);
  if (inp.configAbsPath) L.push(`import * as __config from ${JSON.stringify(inp.configAbsPath)};`);
  L.push(`import { HelipodDurableObject, createWorkerHandler } from ${JSON.stringify(host)};`);
  // R2 blob store — imported only when a bucket binding is configured, so a byte-less deploy pulls in
  // no `@helipod/blobstore-r2` at all.
  if (r2) L.push(`import { R2BlobStore } from "@helipod/blobstore-r2";`);
  L.push("");
  const modEntries = inp.moduleImports.map((m, i) => `${JSON.stringify(m.key)}: m${i}`).join(", ");
  L.push(`const loaded = { schema: (schema && schema.default) ?? schema, modules: { ${modEntries} } };`);
  L.push(inp.configAbsPath ? `const components = (__config.default ?? __config).components ?? [];` : `const components = [];`);
  L.push("");
  L.push(`export class ${inp.doClassName} extends HelipodDurableObject {`);
  L.push(`  appConfig(env) {`);
  if (r2) {
    // `env[r2BindingName]` is the R2 bucket binding; guard so a missing binding degrades to byte-less
    // rather than throwing at boot.
    L.push(`    const __bucket = env && env[${JSON.stringify(r2)}];`);
    L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "", ...(__bucket ? { blobStore: new R2BlobStore({ bucket: __bucket }) } : {}) };`);
  } else {
    L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "" };`);
  }
  L.push(`  }`);
  L.push(`}`);
  L.push("");
  L.push(`export default createWorkerHandler(${JSON.stringify(inp.bindingName)});`);
  return L.join("\n") + "\n";
}
