/**
 * Generate the `_generated/` files from a schema + an analyzed function manifest:
 *   - `dataModel.d.ts` — `DataModel`, `Doc<T>`, `Id<T>`, `TableNames` (from the schema)
 *   - `api.d.ts`       — `FunctionReference`s + the `Api` type (from the manifest)
 *   - `server.ts`      — re-exports `query`/`mutation`/`action` + the generated types
 *
 * These give app code end-to-end types — the Convex-grade DX.
 */
import type { SchemaDefinitionJSON, TableDefinitionJSON, ValidatorJSON } from "@helipod/values";
import { SYSTEM_TABLE_DEFINITIONS } from "@helipod/values";
import { validatorToTsType } from "./validator-to-ts";

export type UdfType = "query" | "mutation" | "action" | "httpAction";
export type Visibility = "public" | "internal";

export interface AnalyzedFunction {
  name: string;
  type: UdfType;
  visibility: Visibility;
  /** TS type string for the arguments (default `any`). */
  argsType?: string;
  /** TS type string for the return value (default `any`). */
  returnsType?: string;
}

export interface AnalyzedModule {
  /** Module path without extension, e.g. "messages" or "admin/users". */
  path: string;
  functions: AnalyzedFunction[];
}

export type AnalyzedFunctionManifest = AnalyzedModule[];

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedBundle {
  dataModel: GeneratedFile;
  api: GeneratedFile;
  internal: GeneratedFile;
  server: GeneratedFile;
  /** Present only when `CodegenInput.tableNumbers` was provided. */
  ids?: GeneratedFile;
  files: GeneratedFile[];
}

export interface ComponentTypeInfo {
  name: string;
  contextType?: { import: string; type: string };
  /**
   * Extra named values this component wants re-exported from `_generated/server.ts`, sourced
   * from `contextType.import` — e.g. `@helipod/scheduler`'s `["cronJobs"]`, so an app's
   * `crons.ts` can do `import { cronJobs } from "./_generated/server"` unchanged. Requires
   * `contextType` to be set (the import path is shared with it); a component with
   * `serverExports` but no `contextType` is a no-op here.
   */
  serverExports?: string[];
}

export interface CodegenOptions {
  header?: string;
  components?: ComponentTypeInfo[];
}

export interface CodegenInput {
  schema: SchemaDefinitionJSON;
  manifest: AnalyzedFunctionManifest;
  components?: ComponentTypeInfo[];
  /** App-table→number map (client-supplied ids spec). When present, `generateAll` emits
   *  `ids.ts`; omitted, codegen behaves exactly as before this feature existed. */
  tableNumbers?: Record<string, number>;
}

const DEFAULT_HEADER = "// Generated by Helipod. Do not edit.\n";

function emitDocumentType(tableName: string, documentType: ValidatorJSON): string {
  const userFields =
    documentType.type === "object"
      ? Object.entries(documentType.value).map(
          ([key, field]) => `${key}${field.optional ? "?" : ""}: ${validatorToTsType(field.fieldType)}`,
        )
      : [];
  const fields = [`_id: Id<${JSON.stringify(tableName)}>`, "_creationTime: number", ...userFields];
  return `{ ${fields.join("; ")} }`;
}

export function generateDataModel(schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  // Built-in app-namespace system tables (e.g. `_storage`) are emitted FIRST, from the canonical
  // definitions in `@helipod/values`, so `Id<"_storage">`/`Doc<"_storage">`/`v.id("_storage")`
  // type-check in user schemas. A user table with a reserved system name never shadows one.
  const systemEntries = Object.entries(SYSTEM_TABLE_DEFINITIONS).map(
    ([name, documentType]) => `  ${name}: { document: ${emitDocumentType(name, documentType)} };`,
  );
  const userTables = (Object.entries(schema.tables) as Array<[string, TableDefinitionJSON]>).filter(
    ([name]) => !(name in SYSTEM_TABLE_DEFINITIONS),
  );
  const userEntries = userTables.map(
    ([name, table]) => `  ${name}: { document: ${emitDocumentType(name, table.documentType)} };`,
  );
  const entries = [...systemEntries, ...userEntries];
  const content = `${options.header ?? DEFAULT_HEADER}import type { GenericId } from "@helipod/values";

export interface DataModel {
${entries.join("\n")}
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
`;
  return { path: "dataModel.d.ts", content };
}

const FUNCTION_REFERENCE_TYPE = `export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};`;

function emitApiModules(manifest: AnalyzedFunctionManifest, visibility: Visibility): string {
  return manifest
    .map((mod) => {
      const fns = mod.functions
        // httpActions are HTTP endpoints (dispatched by route, not by path) — never invoked via
        // ctx.run*/client.query|mutation|action, so they're excluded from the callable api object
        // even though they're listed in the manifest (for codegen/dashboard visibility).
        .filter((f) => f.visibility === visibility && f.type !== "httpAction")
        .map(
          (f) =>
            `    ${f.name}: FunctionReference<"${f.type}", "${visibility}", ${f.argsType ?? "any"}, ${f.returnsType ?? "any"}>;`,
        );
      return `  ${JSON.stringify(mod.path)}: {\n${fns.join("\n")}\n  };`;
    })
    .join("\n");
}

/**
 * `UdfPathOf<A>` — every callable public udfPath (`"module:function"`, matching the runtime
 * `api.messages.send.__path` format exactly — see `@helipod/client`'s `api.ts#getFunctionPath`)
 * reachable from a generated `Api`-shaped type. Spec §(k) decision 6: the durable outbox's
 * `optimisticUpdates` registry (`HelipodClient`'s constructor option, `@helipod/client`) is
 * typed `Partial<Record<UdfPathOf<Api>, OptimisticUpdateFn>>` in app code — the KEYS are narrowed
 * to real udfPaths via this codegen-emitted union; the VALUE type stays one generic function shape
 * (no per-key Args inference), so `@helipod/client` itself only needs a plain string-keyed
 * `Partial<Record<string, OptimisticUpdateFn>>` — `UdfPathOf<Api>` narrows structurally at the call
 * site, nothing in the client package needs to import it.
 */
const UDF_PATH_OF_TYPE = `export type UdfPathOf<A> = {
  [M in keyof A & string]: {
    [F in keyof A[M] & string]: \`\${M}:\${F}\`;
  }[keyof A[M] & string];
}[keyof A & string];`;

export function generateApi(manifest: AnalyzedFunctionManifest, options: CodegenOptions = {}): GeneratedFile {
  const content = `${options.header ?? DEFAULT_HEADER}
${FUNCTION_REFERENCE_TYPE}

export type Api = {
${emitApiModules(manifest, "public")}
};

${UDF_PATH_OF_TYPE}
`;
  return { path: "api.d.ts", content };
}

/**
 * `internal.*` — the counterpart to `Api`/`generateApi`, listing only `visibility: "internal"`
 * functions (a separate file, not folded into `api.d.ts`, so `Api` stays exactly what a
 * client-facing caller should see — nothing internal leaks in by way of sharing a file). This is
 * what `crons.ts` + `ctx.scheduler.runAfter(ms, internal.foo.bar, …)` type-check against — see
 * `@helipod/scheduler`'s design spec §5.2.
 */
export function generateInternalApi(manifest: AnalyzedFunctionManifest, options: CodegenOptions = {}): GeneratedFile {
  const content = `${options.header ?? DEFAULT_HEADER}
${FUNCTION_REFERENCE_TYPE}

export type Internal = {
${emitApiModules(manifest, "internal")}
};
`;
  return { path: "internal.d.ts", content };
}

export function generateServer(_schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  const components = options.components ?? [];
  const ctxComponents = components.filter((c) => c.contextType);
  let augmentation = "";
  if (ctxComponents.length > 0) {
    const fields = ctxComponents
      .map((c) => `    ${c.name}: import("${c.contextType!.import}").${c.contextType!.type};`)
      .join("\n");
    augmentation = `\n// Component context contributions (ctx.<component>), typed.\ndeclare module "@helipod/executor" {\n  interface QueryCtx {\n${fields}\n  }\n  interface MutationCtx {\n${fields}\n  }\n}\n`;
  }

  // Components can re-export extra named values through server.ts (e.g. `@helipod/scheduler`'s
  // `cronJobs`, so `import { cronJobs } from "./_generated/server"` resolves unchanged) — grouped
  // by import path so one component contributing several names emits a single `export { ... }
  // from "..."` line rather than one per name.
  const exportsByImport = new Map<string, string[]>();
  for (const c of components) {
    if (!c.contextType || !c.serverExports || c.serverExports.length === 0) continue;
    const names = exportsByImport.get(c.contextType.import) ?? [];
    names.push(...c.serverExports);
    exportsByImport.set(c.contextType.import, names);
  }
  const componentReexports = [...exportsByImport.entries()]
    .map(([imp, names]) => `export { ${names.join(", ")} } from ${JSON.stringify(imp)};`)
    .join("\n");

  // `api`/`internal` — the runtime path-building proxy (`@helipod/client`'s `anyApi`, typed at
  // this cast site), so `api.messages.list`/`internal.maintenance.purge` are usable as VALUES
  // (not just types) in app code — see `Api`/`Internal` (`./api.d.ts`/`./internal.d.ts`).
  const content = `${options.header ?? DEFAULT_HEADER}export { query, mutation, action, httpAction, httpRouter } from "@helipod/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
export type { Internal } from "./internal";
${componentReexports ? `${componentReexports}\n` : ""}import { anyApi } from "@helipod/client";
import type { Api } from "./api";
import type { Internal } from "./internal";
export const api = anyApi as Api;
export const internal = anyApi as Internal;
${augmentation}`;
  return { path: "server.ts", content };
}

/** `_generated/ids.ts` — the app-table→number map + a typed client-side id mint (client-supplied
 *  ids spec). App tables only: component tables (fullName contains "/") are not insertable by app
 *  code and system tables ("_" prefix) never accept client ids. Emitted only when the composition
 *  provides tableNumbers, so pre-existing codegen consumers are untouched. */
export function generateIds(
  _schema: SchemaDefinitionJSON,
  tableNumbers: Record<string, number>,
  options: CodegenOptions = {},
): GeneratedFile {
  const appTables = Object.entries(tableNumbers)
    .filter(([name]) => !name.includes("/") && !name.startsWith("_"))
    .sort(([a], [b]) => (a < b ? -1 : 1));
  const mapLines = appTables.map(([name, num]) => `  ${JSON.stringify(name)}: ${num},`).join("\n");
  const content = `${options.header ?? DEFAULT_HEADER}import { mintEncodedDocumentId } from "@helipod/id-codec";
import type { Id, TableNames } from "./dataModel";

/** Table numbers for THIS deployment's app tables (embedded in document ids). Regenerate via
 *  \`helipod dev\`/\`helipod codegen\` against the live deployment lineage — the server
 *  validates every client-minted id at insert, so a stale map fails loudly, never silently. */
export const tableNumbers = {
${mapLines}
} as const;

/** Mint a REAL id client-side (same format and entropy as server minting). Mint at
 *  args-construction time, OUTSIDE optimistic updaters (minting is random; updaters must stay
 *  replay-pure and read the id FROM args). Pass it as \`_id\` to an insert and reference it
 *  freely in later queued mutations — see the offline guide's create-then-reference section. */
export function mintId<T extends TableNames>(table: T): Id<T> {
  const num = tableNumbers[table as keyof typeof tableNumbers];
  if (num === undefined) throw new Error(\`unknown table "\${String(table)}" — regenerate _generated/\`);
  return mintEncodedDocumentId(num) as unknown as Id<T>;
}
`;
  return { path: "ids.ts", content };
}

export function generateAll(input: CodegenInput, options: CodegenOptions = {}): GeneratedBundle {
  const dataModel = generateDataModel(input.schema, options);
  const api = generateApi(input.manifest, options);
  const internal = generateInternalApi(input.manifest, options);
  const server = generateServer(input.schema, { ...options, components: input.components ?? options.components });
  const ids = input.tableNumbers ? generateIds(input.schema, input.tableNumbers, options) : undefined;
  const files = ids ? [dataModel, api, internal, server, ids] : [dataModel, api, internal, server];
  return { dataModel, api, internal, server, ids, files };
}
