/**
 * Generate the `_generated/` files from a schema + an analyzed function manifest:
 *   - `dataModel.d.ts` — `DataModel`, `Doc<T>`, `Id<T>`, `TableNames` (from the schema)
 *   - `api.d.ts`       — `FunctionReference`s + the `Api` type (from the manifest)
 *   - `server.ts`      — re-exports `query`/`mutation`/`action` + the generated types
 *
 * These give app code end-to-end types — the Convex-grade DX.
 */
import type { SchemaDefinitionJSON, TableDefinitionJSON, ValidatorJSON } from "@stackbase/values";
import { SYSTEM_TABLE_DEFINITIONS } from "@stackbase/values";
import { validatorToTsType } from "./validator-to-ts";

export type UdfType = "query" | "mutation" | "action" | "httpAction";
export type Visibility = "public" | "internal";

export interface AnalyzedFunction {
  name: string;
  type: UdfType;
  visibility: Visibility;
  /** TS type string for the arguments (default `any`). */
  argsType?: string;
  /** TS type string for the return value (default `any`). */
  returnsType?: string;
}

export interface AnalyzedModule {
  /** Module path without extension, e.g. "messages" or "admin/users". */
  path: string;
  functions: AnalyzedFunction[];
}

export type AnalyzedFunctionManifest = AnalyzedModule[];

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedBundle {
  dataModel: GeneratedFile;
  api: GeneratedFile;
  internal: GeneratedFile;
  server: GeneratedFile;
  files: GeneratedFile[];
}

export interface ComponentTypeInfo {
  name: string;
  contextType?: { import: string; type: string };
  /**
   * Extra named values this component wants re-exported from `_generated/server.ts`, sourced
   * from `contextType.import` — e.g. `@stackbase/scheduler`'s `["cronJobs"]`, so an app's
   * `crons.ts` can do `import { cronJobs } from "./_generated/server"` unchanged. Requires
   * `contextType` to be set (the import path is shared with it); a component with
   * `serverExports` but no `contextType` is a no-op here.
   */
  serverExports?: string[];
}

export interface CodegenOptions {
  header?: string;
  components?: ComponentTypeInfo[];
}

export interface CodegenInput {
  schema: SchemaDefinitionJSON;
  manifest: AnalyzedFunctionManifest;
  components?: ComponentTypeInfo[];
}

const DEFAULT_HEADER = "// Generated by Stackbase. Do not edit.\n";

function emitDocumentType(tableName: string, documentType: ValidatorJSON): string {
  const userFields =
    documentType.type === "object"
      ? Object.entries(documentType.value).map(
          ([key, field]) => `${key}${field.optional ? "?" : ""}: ${validatorToTsType(field.fieldType)}`,
        )
      : [];
  const fields = [`_id: Id<${JSON.stringify(tableName)}>`, "_creationTime: number", ...userFields];
  return `{ ${fields.join("; ")} }`;
}

export function generateDataModel(schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  // Built-in app-namespace system tables (e.g. `_storage`) are emitted FIRST, from the canonical
  // definitions in `@stackbase/values`, so `Id<"_storage">`/`Doc<"_storage">`/`v.id("_storage")`
  // type-check in user schemas. A user table with a reserved system name never shadows one.
  const systemEntries = Object.entries(SYSTEM_TABLE_DEFINITIONS).map(
    ([name, documentType]) => `  ${name}: { document: ${emitDocumentType(name, documentType)} };`,
  );
  const userTables = (Object.entries(schema.tables) as Array<[string, TableDefinitionJSON]>).filter(
    ([name]) => !(name in SYSTEM_TABLE_DEFINITIONS),
  );
  const userEntries = userTables.map(
    ([name, table]) => `  ${name}: { document: ${emitDocumentType(name, table.documentType)} };`,
  );
  const entries = [...systemEntries, ...userEntries];
  const content = `${options.header ?? DEFAULT_HEADER}import type { GenericId } from "@stackbase/values";

export interface DataModel {
${entries.join("\n")}
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
`;
  return { path: "dataModel.d.ts", content };
}

const FUNCTION_REFERENCE_TYPE = `export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};`;

function emitApiModules(manifest: AnalyzedFunctionManifest, visibility: Visibility): string {
  return manifest
    .map((mod) => {
      const fns = mod.functions
        // httpActions are HTTP endpoints (dispatched by route, not by path) — never invoked via
        // ctx.run*/client.query|mutation|action, so they're excluded from the callable api object
        // even though they're listed in the manifest (for codegen/dashboard visibility).
        .filter((f) => f.visibility === visibility && f.type !== "httpAction")
        .map(
          (f) =>
            `    ${f.name}: FunctionReference<"${f.type}", "${visibility}", ${f.argsType ?? "any"}, ${f.returnsType ?? "any"}>;`,
        );
      return `  ${JSON.stringify(mod.path)}: {\n${fns.join("\n")}\n  };`;
    })
    .join("\n");
}

export function generateApi(manifest: AnalyzedFunctionManifest, options: CodegenOptions = {}): GeneratedFile {
  const content = `${options.header ?? DEFAULT_HEADER}
${FUNCTION_REFERENCE_TYPE}

export type Api = {
${emitApiModules(manifest, "public")}
};
`;
  return { path: "api.d.ts", content };
}

/**
 * `internal.*` — the counterpart to `Api`/`generateApi`, listing only `visibility: "internal"`
 * functions (a separate file, not folded into `api.d.ts`, so `Api` stays exactly what a
 * client-facing caller should see — nothing internal leaks in by way of sharing a file). This is
 * what `crons.ts` + `ctx.scheduler.runAfter(ms, internal.foo.bar, …)` type-check against — see
 * `@stackbase/scheduler`'s design spec §5.2.
 */
export function generateInternalApi(manifest: AnalyzedFunctionManifest, options: CodegenOptions = {}): GeneratedFile {
  const content = `${options.header ?? DEFAULT_HEADER}
${FUNCTION_REFERENCE_TYPE}

export type Internal = {
${emitApiModules(manifest, "internal")}
};
`;
  return { path: "internal.d.ts", content };
}

export function generateServer(_schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  const components = options.components ?? [];
  const ctxComponents = components.filter((c) => c.contextType);
  let augmentation = "";
  if (ctxComponents.length > 0) {
    const fields = ctxComponents
      .map((c) => `    ${c.name}: import("${c.contextType!.import}").${c.contextType!.type};`)
      .join("\n");
    augmentation = `\n// Component context contributions (ctx.<component>), typed.\ndeclare module "@stackbase/executor" {\n  interface QueryCtx {\n${fields}\n  }\n  interface MutationCtx {\n${fields}\n  }\n}\n`;
  }

  // Components can re-export extra named values through server.ts (e.g. `@stackbase/scheduler`'s
  // `cronJobs`, so `import { cronJobs } from "./_generated/server"` resolves unchanged) — grouped
  // by import path so one component contributing several names emits a single `export { ... }
  // from "..."` line rather than one per name.
  const exportsByImport = new Map<string, string[]>();
  for (const c of components) {
    if (!c.contextType || !c.serverExports || c.serverExports.length === 0) continue;
    const names = exportsByImport.get(c.contextType.import) ?? [];
    names.push(...c.serverExports);
    exportsByImport.set(c.contextType.import, names);
  }
  const componentReexports = [...exportsByImport.entries()]
    .map(([imp, names]) => `export { ${names.join(", ")} } from ${JSON.stringify(imp)};`)
    .join("\n");

  // `api`/`internal` — the runtime path-building proxy (`@stackbase/client`'s `anyApi`, typed at
  // this cast site), so `api.messages.list`/`internal.maintenance.purge` are usable as VALUES
  // (not just types) in app code — see `Api`/`Internal` (`./api.d.ts`/`./internal.d.ts`).
  const content = `${options.header ?? DEFAULT_HEADER}export { query, mutation, action, httpAction, httpRouter } from "@stackbase/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
export type { Internal } from "./internal";
${componentReexports ? `${componentReexports}\n` : ""}import { anyApi } from "@stackbase/client";
import type { Api } from "./api";
import type { Internal } from "./internal";
export const api = anyApi as Api;
export const internal = anyApi as Internal;
${augmentation}`;
  return { path: "server.ts", content };
}

export function generateAll(input: CodegenInput, options: CodegenOptions = {}): GeneratedBundle {
  const dataModel = generateDataModel(input.schema, options);
  const api = generateApi(input.manifest, options);
  const internal = generateInternalApi(input.manifest, options);
  const server = generateServer(input.schema, { ...options, components: input.components ?? options.components });
  return { dataModel, api, internal, server, files: [dataModel, api, internal, server] };
}
