/**
 * Generate the `_generated/` files from a schema + an analyzed function manifest:
 *   - `dataModel.d.ts` — `DataModel`, `Doc<T>`, `Id<T>`, `TableNames` (from the schema)
 *   - `api.d.ts`       — `FunctionReference`s + the `Api` type (from the manifest)
 *   - `server.ts`      — re-exports `query`/`mutation`/`action` + the generated types
 *
 * These give app code end-to-end types — the Convex-grade DX.
 */
import type { SchemaDefinitionJSON, TableDefinitionJSON, ValidatorJSON } from "@stackbase/values";
import { validatorToTsType } from "./validator-to-ts";

export type UdfType = "query" | "mutation" | "action";
export type Visibility = "public" | "internal";

export interface AnalyzedFunction {
  name: string;
  type: UdfType;
  visibility: Visibility;
  /** TS type string for the arguments (default `any`). */
  argsType?: string;
  /** TS type string for the return value (default `any`). */
  returnsType?: string;
}

export interface AnalyzedModule {
  /** Module path without extension, e.g. "messages" or "admin/users". */
  path: string;
  functions: AnalyzedFunction[];
}

export type AnalyzedFunctionManifest = AnalyzedModule[];

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedBundle {
  dataModel: GeneratedFile;
  api: GeneratedFile;
  server: GeneratedFile;
  files: GeneratedFile[];
}

export interface ComponentTypeInfo {
  name: string;
  contextType?: { import: string; type: string };
}

export interface CodegenOptions {
  header?: string;
  components?: ComponentTypeInfo[];
}

export interface CodegenInput {
  schema: SchemaDefinitionJSON;
  manifest: AnalyzedFunctionManifest;
  components?: ComponentTypeInfo[];
}

const DEFAULT_HEADER = "// Generated by Stackbase. Do not edit.\n";

function emitDocumentType(tableName: string, documentType: ValidatorJSON): string {
  const userFields =
    documentType.type === "object"
      ? Object.entries(documentType.value).map(
          ([key, field]) => `${key}${field.optional ? "?" : ""}: ${validatorToTsType(field.fieldType)}`,
        )
      : [];
  const fields = [`_id: Id<${JSON.stringify(tableName)}>`, "_creationTime: number", ...userFields];
  return `{ ${fields.join("; ")} }`;
}

export function generateDataModel(schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  const tables = Object.entries(schema.tables) as Array<[string, TableDefinitionJSON]>;
  const entries = tables.map(([name, table]) => `  ${name}: { document: ${emitDocumentType(name, table.documentType)} };`);
  const content = `${options.header ?? DEFAULT_HEADER}import type { GenericId } from "@stackbase/values";

export interface DataModel {
${entries.join("\n")}
}

export type TableNames = keyof DataModel;
export type Id<TableName extends TableNames> = GenericId<TableName>;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
`;
  return { path: "dataModel.d.ts", content };
}

export function generateApi(manifest: AnalyzedFunctionManifest, options: CodegenOptions = {}): GeneratedFile {
  const modules = manifest
    .map((mod) => {
      const fns = mod.functions
        .filter((f) => f.visibility === "public")
        .map(
          (f) =>
            `    ${f.name}: FunctionReference<"${f.type}", "public", ${f.argsType ?? "any"}, ${f.returnsType ?? "any"}>;`,
        );
      return `  ${JSON.stringify(mod.path)}: {\n${fns.join("\n")}\n  };`;
    })
    .join("\n");

  const content = `${options.header ?? DEFAULT_HEADER}
export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
${modules}
};
`;
  return { path: "api.d.ts", content };
}

export function generateServer(_schema: SchemaDefinitionJSON, options: CodegenOptions = {}): GeneratedFile {
  const ctxComponents = (options.components ?? []).filter((c) => c.contextType);
  let augmentation = "";
  if (ctxComponents.length > 0) {
    const fields = ctxComponents
      .map((c) => `    ${c.name}: import("${c.contextType!.import}").${c.contextType!.type};`)
      .join("\n");
    augmentation = `\n// Component context contributions (ctx.<component>), typed.\ndeclare module "@stackbase/executor" {\n  interface QueryCtx {\n${fields}\n  }\n  interface MutationCtx {\n${fields}\n  }\n}\n`;
  }
  const content = `${options.header ?? DEFAULT_HEADER}export { query, mutation, action } from "@stackbase/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
${augmentation}`;
  return { path: "server.ts", content };
}

export function generateAll(input: CodegenInput, options: CodegenOptions = {}): GeneratedBundle {
  const dataModel = generateDataModel(input.schema, options);
  const api = generateApi(input.manifest, options);
  const server = generateServer(input.schema, { ...options, components: input.components ?? options.components });
  return { dataModel, api, server, files: [dataModel, api, server] };
}
