// Generated by Stackbase. Do not edit.
export { query, mutation, action, httpAction, httpRouter } from "@stackbase/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
export type { Internal } from "./internal";
export { cronJobs } from "@stackbase/scheduler";
import { anyApi } from "@stackbase/client";
import type { Api } from "./api";
import type { Internal } from "./internal";
export const api = anyApi as Api;
export const internal = anyApi as Internal;

// Component context contributions (ctx.<component>), typed.
declare module "@stackbase/executor" {
  interface QueryCtx {
    auth: import("@stackbase/auth").AuthContext;
    scheduler: import("@stackbase/scheduler").SchedulerContext;
    workflow: import("@stackbase/workflow").WorkflowContext;
  }
  interface MutationCtx {
    auth: import("@stackbase/auth").AuthContext;
    scheduler: import("@stackbase/scheduler").SchedulerContext;
    workflow: import("@stackbase/workflow").WorkflowContext;
  }
}
