// Generated by Helipod. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "messages": {
    list: FunctionReference<"query", "public", any, any>;
    send: FunctionReference<"mutation", "public", { channelId: string; body: string }, any>;
    sendMisrouted: FunctionReference<"mutation", "public", { channelId: string; misroutedTo: string; body: string }, any>;
  };
  "notes": {
    add: FunctionReference<"mutation", "public", any, any>;
    addViaAction: FunctionReference<"action", "public", any, any>;
    get: FunctionReference<"query", "public", any, any>;
    list: FunctionReference<"query", "public", any, any>;
    update: FunctionReference<"mutation", "public", any, any>;
  };
};
