// Generated by Helipod. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "files": {
    createUpload: FunctionReference<"mutation", "public", any, any>;
    getMeta: FunctionReference<"query", "public", any, any>;
    getUrl: FunctionReference<"query", "public", any, any>;
    list: FunctionReference<"query", "public", any, any>;
    remove: FunctionReference<"mutation", "public", any, any>;
    save: FunctionReference<"mutation", "public", any, any>;
  };
};
