/**
 * Pure generator for the `helipod build` entrypoint. `bun build --compile` only bundles STATIC
 * imports, so we emit static imports of the app's modules/schema/config (+ embedded dashboard files)
 * and reconstruct the `{schema, modules}` shape `loadFunctionsDir` returns at runtime. `JSON.stringify`
 * on every path/key guards against quotes/backslashes breaking the generated source.
 */
export interface EntryInputs {
  moduleImports: Array<{ key: string; absPath: string }>;
  schemaAbsPath: string;
  configAbsPath: string | null;
  dashboardFiles: Array<{ urlPath: string; absPath: string }> | null;
}

export function generateEntrySource(inp: EntryInputs): string {
  const L: string[] = ["// AUTO-GENERATED by `helipod build` — do not edit."];
  inp.moduleImports.forEach((m, i) => L.push(`import * as m${i} from ${JSON.stringify(m.absPath)};`));
  L.push(`import schema from ${JSON.stringify(inp.schemaAbsPath)};`);
  if (inp.configAbsPath) L.push(`import * as __config from ${JSON.stringify(inp.configAbsPath)};`);
  (inp.dashboardFiles ?? []).forEach((d, i) => L.push(`import d${i} from ${JSON.stringify(d.absPath)} with { type: "file" };`));
  L.push(`import { runBinaryServer } from "@helipod/cli";`);
  L.push("");
  const modEntries = inp.moduleImports.map((m, i) => `${JSON.stringify(m.key)}: m${i}`).join(", ");
  L.push(`const loaded = { schema, modules: { ${modEntries} } };`);
  L.push(inp.configAbsPath ? `const components = (__config.default ?? __config).components ?? [];` : `const components = [];`);
  if (inp.dashboardFiles) {
    const dEntries = inp.dashboardFiles.map((d, i) => `${JSON.stringify(d.urlPath)}: d${i}`).join(", ");
    L.push(`const dashboard = { ${dEntries} };`);
    L.push(`await runBinaryServer(loaded, components, dashboard);`);
  } else {
    L.push(`await runBinaryServer(loaded, components, undefined);`);
  }
  return L.join("\n") + "\n";
}
