/* Stackbase Enterprise. Licensed under the Stackbase Commercial License — see ee/LICENSE. */

/**
 * Pure generator for a MULTI-SHARD Cloudflare Worker/DO entrypoint — the ee twin of the free host's
 * `generateWorkerEntrySource` (`packages/runtime-cloudflare/src/worker-entry.ts`). Same static-import
 * discipline (a Worker bundle can no more dir-scan `convex/` than a `bun build --compile` binary can),
 * and it emits the SAME concrete DO class — a plain `StackbaseDurableObject` subclass from the FREE
 * package, unmodified (M1: a shard-DO IS Slice 3). The ONLY difference from the single-shard entry is
 * the `export default`: `createShardWorkerHandler(...)` (this ee package) instead of
 * `createWorkerHandler(...)` (the free package).
 *
 * This is the licensing switch made concrete: an app's Worker entry chooses single- vs multi-shard by
 * WHICH handler it default-exports. The free host never imports this generator.
 */
export interface ShardWorkerEntryInputs {
  moduleImports: Array<{ key: string; absPath: string }>;
  schemaAbsPath: string;
  configAbsPath: string | null;
  /** The shard-DO `durable_objects` binding name (e.g. `"STACKBASE_DO"`). */
  bindingName: string;
  /** The exported DO class name the `wrangler.jsonc` migration references (e.g. `"StackbaseDO"`). */
  doClassName: string;
  /** Routing mode: "key" (default) or "hash". */
  mode?: "key" | "hash";
  /** For mode "hash": the fixed shard count N. */
  numShards?: number;
  /** The env var the admin key is read from at DO boot (default `STACKBASE_ADMIN_KEY`). */
  adminKeyEnvVar?: string;
  /** Override the free host package import specifier (the in-repo fixture uses this). */
  hostPackage?: string;
  /** Override the ee shard package import specifier (the in-repo fixture uses this). */
  shardPackage?: string;
}

export function generateShardWorkerEntrySource(inp: ShardWorkerEntryInputs): string {
  const host = inp.hostPackage ?? "@stackbase/runtime-cloudflare";
  const shard = inp.shardPackage ?? "@stackbase/runtime-cloudflare-shard";
  const adminEnv = inp.adminKeyEnvVar ?? "STACKBASE_ADMIN_KEY";
  const mode = inp.mode ?? "key";
  const L: string[] = ["// AUTO-GENERATED by `@stackbase/runtime-cloudflare-shard` worker-entry — do not edit."];
  inp.moduleImports.forEach((m, i) => L.push(`import * as m${i} from ${JSON.stringify(m.absPath)};`));
  L.push(`import schema from ${JSON.stringify(inp.schemaAbsPath)};`);
  if (inp.configAbsPath) L.push(`import * as __config from ${JSON.stringify(inp.configAbsPath)};`);
  L.push(`import { StackbaseDurableObject } from ${JSON.stringify(host)};`);
  L.push(`import { createShardWorkerHandler } from ${JSON.stringify(shard)};`);
  L.push("");
  const modEntries = inp.moduleImports.map((m, i) => `${JSON.stringify(m.key)}: m${i}`).join(", ");
  L.push(`const loaded = { schema: (schema && schema.default) ?? schema, modules: { ${modEntries} } };`);
  L.push(inp.configAbsPath ? `const components = (__config.default ?? __config).components ?? [];` : `const components = [];`);
  L.push("");
  L.push(`export class ${inp.doClassName} extends StackbaseDurableObject {`);
  L.push(`  appConfig(env) {`);
  L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "" };`);
  L.push(`  }`);
  L.push(`}`);
  L.push("");
  // `loaded` is passed to the router so a POST /api/run can DERIVE a mutation's shard key from its args.
  const routeOpts = mode === "hash"
    ? `{ mode: "hash", numShards: ${JSON.stringify(inp.numShards ?? 1)}, loaded }`
    : `{ mode: "key", loaded }`;
  L.push(`export default createShardWorkerHandler(${JSON.stringify(inp.bindingName)}, ${routeOpts});`);
  return L.join("\n") + "\n";
}
