/* Stackbase Enterprise. Licensed under the Stackbase Commercial License — see ee/LICENSE. */

/**
 * Pure generator for a MULTI-SHARD Cloudflare Worker/DO entrypoint — the ee twin of the free host's
 * `generateWorkerEntrySource` (`packages/runtime-cloudflare/src/worker-entry.ts`). Same static-import
 * discipline (a Worker bundle can no more dir-scan `convex/` than a `bun build --compile` binary can),
 * and it emits the SAME concrete DO class — a plain `StackbaseDurableObject` subclass from the FREE
 * package, unmodified (M1: a shard-DO IS Slice 3). The ONLY difference from the single-shard entry is
 * the `export default`: `createShardWorkerHandler(...)` (this ee package) instead of
 * `createWorkerHandler(...)` (the free package).
 *
 * This is the licensing switch made concrete: an app's Worker entry chooses single- vs multi-shard by
 * WHICH handler it default-exports. The free host never imports this generator.
 *
 * File storage (`r2BindingName`) is wired the same way the free generator wires it: since every
 * shard-DO is that SAME unmodified `StackbaseDurableObject`, its `appConfig()` already knows how to use
 * a `blobStore` — this generator just needs to construct one from the R2 binding and thread it through,
 * identically for every shard.
 */
export interface ShardWorkerEntryInputs {
  moduleImports: Array<{ key: string; absPath: string }>;
  schemaAbsPath: string;
  configAbsPath: string | null;
  /** The shard-DO `durable_objects` binding name (e.g. `"STACKBASE_DO"`). */
  bindingName: string;
  /** The exported DO class name the `wrangler.jsonc` migration references (e.g. `"StackbaseDO"`). */
  doClassName: string;
  /** Routing mode: "key" (default) or "hash". */
  mode?: "key" | "hash";
  /** For mode "hash": the fixed shard count N. */
  numShards?: number;
  /** Opt-in geographic placement source (b): derive a shard-DO's `locationHint` from a `"<hint>:<rest>"`
   *  prefix on the shard-key value. Off by default. */
  regionPrefixedKeys?: boolean;
  /** The env var the admin key is read from at DO boot (default `STACKBASE_ADMIN_KEY`). */
  adminKeyEnvVar?: string;
  /** Override the free host package import specifier (the in-repo fixture uses this). */
  hostPackage?: string;
  /** Override the ee shard package import specifier (the in-repo fixture uses this). */
  shardPackage?: string;
  /**
   * The `r2_buckets` binding name in `wrangler.jsonc` (e.g. `"STORAGE_BUCKET"`). Set to enable file
   * storage on the shard-DO: the generated `appConfig` constructs an `R2BlobStore` over
   * `env[r2BindingName]` and threads it as `blobStore`, so `ctx.storage` + the `/api/storage/*` routes
   * work on every shard-DO — same mechanism as the free single-shard host
   * (`generateWorkerEntrySource`'s `r2BindingName`, `packages/runtime-cloudflare/src/worker-entry.ts`),
   * since each shard-DO is that SAME unmodified `StackbaseDurableObject` class. Absent → no R2 import,
   * `blobStore` omitted, file storage inert (byte-less deploy, unchanged).
   */
  r2BindingName?: string;
}

export function generateShardWorkerEntrySource(inp: ShardWorkerEntryInputs): string {
  const host = inp.hostPackage ?? "@stackbase/runtime-cloudflare";
  const shard = inp.shardPackage ?? "@stackbase/runtime-cloudflare-shard";
  const adminEnv = inp.adminKeyEnvVar ?? "STACKBASE_ADMIN_KEY";
  const mode = inp.mode ?? "key";
  const r2 = inp.r2BindingName;
  const L: string[] = ["// AUTO-GENERATED by `@stackbase/runtime-cloudflare-shard` worker-entry — do not edit."];
  inp.moduleImports.forEach((m, i) => L.push(`import * as m${i} from ${JSON.stringify(m.absPath)};`));
  L.push(`import schema from ${JSON.stringify(inp.schemaAbsPath)};`);
  if (inp.configAbsPath) L.push(`import * as __config from ${JSON.stringify(inp.configAbsPath)};`);
  L.push(`import { StackbaseDurableObject } from ${JSON.stringify(host)};`);
  L.push(`import { createShardWorkerHandler } from ${JSON.stringify(shard)};`);
  // R2 blob store — imported only when a bucket binding is configured, so a byte-less deploy pulls in
  // no `@stackbase/blobstore-r2` at all (mirrors the free single-shard generator verbatim).
  if (r2) L.push(`import { R2BlobStore } from "@stackbase/blobstore-r2";`);
  L.push("");
  const modEntries = inp.moduleImports.map((m, i) => `${JSON.stringify(m.key)}: m${i}`).join(", ");
  L.push(`const loaded = { schema: (schema && schema.default) ?? schema, modules: { ${modEntries} } };`);
  L.push(inp.configAbsPath ? `const components = (__config.default ?? __config).components ?? [];` : `const components = [];`);
  L.push("");
  L.push(`export class ${inp.doClassName} extends StackbaseDurableObject {`);
  L.push(`  appConfig(env) {`);
  if (r2) {
    // `env[r2BindingName]` is the R2 bucket binding, shared across every shard-DO instance; guard so a
    // missing binding degrades to byte-less rather than throwing at boot.
    L.push(`    const __bucket = env && env[${JSON.stringify(r2)}];`);
    L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "", ...(__bucket ? { blobStore: new R2BlobStore({ bucket: __bucket }) } : {}) };`);
  } else {
    L.push(`    return { loaded, components, adminKey: (env && env[${JSON.stringify(adminEnv)}]) ?? "" };`);
  }
  L.push(`  }`);
  L.push(`}`);
  L.push("");
  // `loaded` is passed to the router so a POST /api/run can DERIVE a mutation's shard key from its args.
  // `regionPrefixedKeys` (opt-in) enables the `"<hint>:<rest>"`-prefix placement source.
  const rpk = inp.regionPrefixedKeys ? ", regionPrefixedKeys: true" : "";
  const routeOpts = mode === "hash"
    ? `{ mode: "hash", numShards: ${JSON.stringify(inp.numShards ?? 1)}, loaded${rpk} }`
    : `{ mode: "key", loaded${rpk} }`;
  L.push(`export default createShardWorkerHandler(${JSON.stringify(inp.bindingName)}, ${routeOpts});`);
  return L.join("\n") + "\n";
}
