// Generated by Helipod. Do not edit.

export type FunctionReference<
  Type extends "query" | "mutation" | "action",
  Vis extends "public" | "internal" = "public",
  Args = any,
  Returns = any,
> = {
  readonly __type: Type;
  readonly __visibility: Vis;
  readonly __args: Args;
  readonly __returns: Returns;
};

export type Api = {
  "messages": {
    list: FunctionReference<"query", "public", { channelId: string }, any>;
    send: FunctionReference<"mutation", "public", { channelId: string; body: string }, any>;
    sendWrongShard: FunctionReference<"mutation", "public", { channelId: string; otherChannelId: string; body: string }, any>;
  };
};

export type UdfPathOf<A> = {
  [M in keyof A & string]: {
    [F in keyof A[M] & string]: `${M}:${F}`;
  }[keyof A[M] & string];
}[keyof A & string];
